# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: '2'
services:
#  firefox:
#    image: selenium/node-firefox:3.14.0-europium
#    volumes:
#      - /dev/shm:/dev/shm
#    depends_on:
#      - hub
#    environment:
#      HUB_HOST: hub

  chrome:
    image: selenium/node-chrome:3.14.0-europium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  hub:
    image: selenium/hub:3.14.0-europium
    ports:
      - "4444:4444"

  tests:
    build:
      context: .
    command: mvn clean verify -Dit.test=TestRunnerIT
    depends_on:
      - hub
    links:
     - hub
     - chrome
    volumes:
     - /tmp/serenitytests:/app/target/failsafe-reports
#    volumes:
#     - ./report:/test/RtiTestsHtmlreport